// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInstallMATLABAddOn creates a new instance of MockInstallMATLABAddOn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallMATLABAddOn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallMATLABAddOn {
	mock := &MockInstallMATLABAddOn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallMATLABAddOn is an autogenerated mock type for the InstallMATLABAddOn type
type MockInstallMATLABAddOn struct {
	mock.Mock
}

type MockInstallMATLABAddOn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallMATLABAddOn) EXPECT() *MockInstallMATLABAddOn_Expecter {
	return &MockInstallMATLABAddOn_Expecter{mock: &_m.Mock}
}

// StartAndWaitForCompletion provides a mock function for the type MockInstallMATLABAddOn
func (_mock *MockInstallMATLABAddOn) StartAndWaitForCompletion(ctx context.Context) messages.Error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAndWaitForCompletion")
	}

	var r0 messages.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context) messages.Error); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.Error)
		}
	}
	return r0
}

// MockInstallMATLABAddOn_StartAndWaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAndWaitForCompletion'
type MockInstallMATLABAddOn_StartAndWaitForCompletion_Call struct {
	*mock.Call
}

// StartAndWaitForCompletion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstallMATLABAddOn_Expecter) StartAndWaitForCompletion(ctx interface{}) *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call {
	return &MockInstallMATLABAddOn_StartAndWaitForCompletion_Call{Call: _e.mock.On("StartAndWaitForCompletion", ctx)}
}

func (_c *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call) Run(run func(ctx context.Context)) *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call) Return(error messages.Error) *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call) RunAndReturn(run func(ctx context.Context) messages.Error) *MockInstallMATLABAddOn_StartAndWaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}
